name: C Build for Web Server

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Install GCC and necessary build tools
      - name: Install GCC
        run: sudo apt-get update && sudo apt-get install build-essential -y

      # Compile the C program (specific project + shared folder)
      - name: Compile C Program
        run: |
          gcc -I/src/web_server_from_scratch src/web_server_from_scratch/*.c src/shared/*.c -o web_server_from_scratch

      # Uncomment to run the compiled program (ensure it’s correct)
      # - name: Run Program
      #   run: ./web_server_from_scratch

      # Optional: Clean up after running
      # - name: Clean up
      #   run: rm -f web_server_from_scratch
